### ISSUE TITLE
Error loading angular2-tree-diagram.js

### ISSUE THREAD

**Issue by h0ujun** [artbelikov/angular2-tree-diagram#1]
After doing npm i, I added it in module using:
import { TreeDiagram } from 'angular2-tree-diagram';

Then when I use it, it is showing this error:
ERROR Error: Uncaught (in promise): Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3XXX/node_modules/angular2-tree-diagram.js

Checked node_modules, it does not have any js file... any steps on how to use this module/directive? Thanks

**Comment by artbelikov** [comment]
h0ujun
Not shure how your build sustem works. It should be node_modules/angular2-tree-diagram/index.ts
This is not compiled module.
Use it like so
import { TreeDiagram } from 'angular2-tree-diagram';
...
Then in your module
 imports: [
       TreeDiagram
  ],
