### ISSUE TITLE
What are all the Config options available?

### ISSUE THREAD

**Issue by keshav1007** [artbelikov/angular2-tree-diagram#10]
What are all the config options available? Is there config to prevent user from editing like adding/deleting nodes from the tree

**Comment by artbelikov** [comment]
Hi! No such config. Please consider making a fork.On Sep 20, 2018 13:26, keshav1007 <notifications@github.com> wrote:What are all the config options available? Is there config to prevent user from editing like adding/deleting nodes from the tree
