### ISSUE TITLE
Crucial: Add License to the project

### ISSUE THREAD

**Issue by stavrosicsd** [artbelikov/angular2-tree-diagram#15]
@artbelikov would you kindly add a license to the project (e.g. MIT, Apache etc)? Having no license does not allow people to use your open source code in any way (commercial, private etc). For more information see:
https://choosealicense.com/no-permission/
and
github/choosealicense.com#196

Thanks in advance

**Comment by artbelikov** [comment]
Okey, good idea.On Feb 2, 2019 00:26, stavrosicsd <notifications@github.com> wrote:@artbelikov would you kindly add a license to the project (e.g. MIT, Apache etc)? Having no license does not allow people to use your open source code in any way (commercial, private etc). For more information see:
https://choosealicense.com/no-permission/
and
github/choosealicense.com#196
Thanks in advance
