### ISSUE TITLE
Imposible to make it work

### ISSUE THREAD

**Issue by JoanJosep33** [artbelikov/angular2-tree-diagram#17]
Hello, after I tried to follow the example, it results impossible to make works this component. Could you provide a full example about how to import the module? 

Even if I import from node_modules or 'angular2-tree-diagram' does not seem to work. Your example is incompleted. 

Thank you so much

**Comment by JoanJosep33** [comment]
`ERROR in ./node_modules/angular2-tree-diagram/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: ...\node_modules\angular2-tree-diagram\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue
in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (...\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:767:23)
    at plugin.done.then (...\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
i ｢wdm｣: Failed to compile.`

**Comment by artbelikov** [comment]
Hello.
The error is pretty much says it.
"is missing from the TypeScript compilation"
You see, I haven't released it compiled to js. You have few options.
1. Make it auto-compile on build and pull request it.
2. Adjust your webpack to build it from node_modules.
3. Copy as-is to your working directory.
