### ISSUE TITLE
Template parse error: Can't bind to 'data' since it isn't a known property of 'tree-diagram'

### ISSUE THREAD

**Issue by InnovationZone** [artbelikov/angular2-tree-diagram#18]
I've added the library to my angular project as specified on the NPM page. 
When I build the project, I get this error:

`Uncaught Error: Template parse errors:
Can't bind to 'data' since it isn't a known property of 'tree-diagram'.
1. If 'tree-diagram' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tree-diagram' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<div class="col-9">
    <tree-diagram [ERROR ->][data]="data"></tree-diagram>
</div>
"): ng:///AppModule/PanelComponent.html@1:18
'tree-diagram' is not a known element:
1. If 'tree-diagram' is an Angular component, then verify that it is part of this module.
2. If 'tree-diagram' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<div class="col-9">
    [ERROR ->]<tree-diagram [data]="data"></tree-diagram>
</div>
`

In my AppModule, I have done that:

`import { TreeDiagram } from 'angular2-tree-diagram'
...
imports: [
    BrowserModule,
    UiModule,
    TreeDiagram
  ],

I've noticed on some other closed issues that the module is not compiled. That explains the issue, but even if I add the module to the TypeScript compiler as follows:

`{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": [
      "xrm",
      "jquery",
      "jstree"
    ]
  },
  "include": [
    "../node_modules/angular2-tree-diagram/*"
  ],
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
`

and run **ng build**, it gives the following error:

**ERROR in No NgModule metadata found for 'AppModule'**

**Comment by artbelikov** [comment]
try now please
