### ISSUE TITLE
Multiline name of node problem

### ISSUE THREAD

**Issue by sbodak** [artbelikov/angular2-tree-diagram#2]
I've detected unexpected behavior during adding multiline name of node.

After click outside of edited node box, node's name is duplicated. 
The same situation is during use hide&show button of parent node.

[https://ibb.co/eyOvD6](https://ibb.co/eyOvD6)

Thanks for fix in advance.

**Comment by artbelikov** [comment]
Thanks for reporting. Should work fine now.
