### ISSUE TITLE
AOT compile fails

### ISSUE THREAD

**Issue by abishek** [artbelikov/angular2-tree-diagram#23]
When I try to compile in AOT or --prod, the build fails with 
ERROR in Unexpected value 'undefined' exported by the module 'TreeDiagramModule in .../node_modules/angular2-tree-diagram/angular2-tree-diagram.d.ts'

If I remove the --prod flag or the --aot flag, compilation goes through and everything works as expected. 

How can I make this work?

**Comment by artbelikov** [comment]
Thanks for report. I'll look into it at weekend.03.02.2020, 17:15, "Abishek Goda" <notifications@github.com>:When I try to compile in AOT or --prod, the build fails with
ERROR in Unexpected value 'undefined' exported by the module 'TreeDiagramModule in .../node_modules/angular2-tree-diagram/angular2-tree-diagram.d.ts'
If I remove the --prod flag or the --aot flag, compilation goes through and everything works as expected.
How can I make this work?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением,Артём

**Comment by PrathameshAware** [comment]
I'am facing the same problem when trying do a production build. 
Are there any leads on this issue?

**Comment by artbelikov** [comment]
Sorry guys, I forgot about it. I'll look into it today.On Feb 13, 2020 17:12, PrathameshAware <notifications@github.com> wrote:I'am facing the same problem when trying do a production build.
Are there any leads on this issue?

**Comment by artbelikov** [comment]
I updated the lib to angular 9 version and published it to npm. If you use source then you should run `npm run build-lib` first.

**Comment by PrathameshAware** [comment]
@artbelikov I updated to latest 1.2.0 version, but this is not solving the issue. Now I am getting few extra errors in addition to the last line after running `ng build --prod`
![image](https://user-images.githubusercontent.com/31981862/74506500-c8394b80-4f1f-11ea-8b86-57e5d7cd0ab5.png)

**Comment by artbelikov** [comment]
Impossibru. Okay, I'll try again today.

**Comment by artbelikov** [comment]
Well there is two points.
I have not encountered any errors upon building with --prod.
It is a common latest problem.
Try to update to the latest typescript/angular.
https://github.com/storybookjs/storybook/issues/9463

**Comment by PrathameshAware** [comment]
@artbelikov Well I tried upgrading from angular 8 to 9. Used typescript 3.7.2 and all various kinds of combination.
This are my dependencies in `package.json` after reverting back to angular 8
`"dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^9.0.0",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@pxblue/themes": "^2.1.0",
    "@syncfusion/ej2-angular-base": "^17.4.39",
    "@syncfusion/ej2-angular-inputs": "^17.2.47",
    "angular-csv-ext": "^1.0.2",
    "angular-user-idle": "^2.2.1",
    "angular2-tree-diagram": "1.2.0",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "highcharts": "^8.0.0",
    "highcharts-angular": "^2.4.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "ngx-daterangepicker-material": "^2.1.11",
    "ngx-select-dropdown": "^1.3.0",
    "ngx-toastr": "^10.2.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.9.0",
    "underscore": "^1.9.1",
    "zipcode-to-timezone": "0.0.9",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-builders/jest": "^8.3.2",
    "@angular-devkit/build-angular": "~0.803.21",
    "@angular/cli": "~9.0.2",
    "@angular/core": "~9.0.1",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^25.1.2",
    "@types/node": "^8.9.5",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^25.1.0",
    "node-sass": "^4.13.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "3.5.3"
  }`

I tried angular2-tree-diagram with versions 1.1.0, 1.1.1 and latest 1.2.0 and each time I am getting consistent error on prod build only for **TreeDiagramModule**

![image](https://user-images.githubusercontent.com/31981862/74608319-042e0580-5106-11ea-9ccc-a3e6ca199c98.png)

Sorry for troubling again.

**Comment by artbelikov** [comment]
Maybe it will be faster for you to use sources. Cos I have full time job and cant support librarry very often. Go see how it builds demo page, see if there is any difference with your project.

**Comment by PrathameshAware** [comment]
I think I might have got what's the issue was:
I tried `ng build --prod` on source files and got below error - 
![image](https://user-images.githubusercontent.com/31981862/74630453-a4287500-5180-11ea-892f-6fae69228b3f.png)

Seems like `TreeDiagramModule` was incorrectly referenced. It should be 
```
import { TreeDiagramModule } from 'projects/ng-tree-diagram/src/lib';
```

**Comment by PrathameshAware** [comment]
I think I might have got what's the issue was:
I tried `ng build --prod` on source files and got below error - 
![image](https://user-images.githubusercontent.com/31981862/74630754-4a747a80-5181-11ea-9697-98d8d1a09c7a.png)


Seems like `TreeDiagramModule` was incorrectly referenced. It should be 
```
import { TreeDiagramModule } from 'projects/ng-tree-diagram/src/lib';
```

**Comment by PrathameshAware** [comment]
Seems like the versions till `1.1.1` didn't support AOT (and thus prod build).
After upgrading my app to Angular 9 and using `1.2.0` everything is working fine.
Thanks and cheers @artbelikov ! 👍 😄
