### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by jendison** [artbelikov/angular2-tree-diagram#4]
Hi @artbelikov ,
I use [angular-starter](https://github.com/gdi2290/angular-starter) which using Webpack3 Angular5.

In a lazy module, I import {TreeDiagram} from 'angular2-tree-diagram';

But however,when I run "npm start",  I got following error ：

> ERROR in ./node_modules/angular2-tree-diagram/index.ts
> Module build failed: Error: 
**/node_modules/angular2-tree-diagram/index.ts is not part of the compilation output. Please check the other error messages for details.
>     at AngularCompilerPlugin.getCompiledFile (**/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
>     at plugin.done.then (**/node_modules/@ngtools/webpack/src/loader.js:467:39)
>     at process._tickCallback (internal/process/next_tick.js:109:7)
>  @ ./src/app/app.module.ts 32:0-58
>  @ ./src/app/index.ts
>  @ ./src/main.browser.ts
>  @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

Pls help me to fix this.
Thank you!

**Comment by artbelikov** [comment]
Hi.
As you may notice I publish the module uncompiled. So you have to compile it yourself. That may be not the best practice, but solution is quite simple. Setup your typescript compilation that way, so it doesn't ignore folder angular2-tree-diagram inside node_modules.

**Comment by saleemnasa** [comment]
But How can we do it?
where do I need to add the angular2-tree-diagram folder path to get its ts files compiled?
