### ISSUE TITLE
Error Module

### ISSUE THREAD

**Issue by SebasPZ82** [artbelikov/angular2-tree-diagram#5]
![capture](https://user-images.githubusercontent.com/25773417/37123247-781a9306-2231-11e8-862a-77687182931f.PNG)

I have a problem with the import, I do not know if they have any solution or if they are doing something wrong ???????????

**Comment by artbelikov** [comment]
Hi.
As you may notice I publish the module uncompiled. So you have to compile it yourself. That may be not the best practice, but solution is quite simple. Setup your typescript compilation that way, so it doesn't ignore folder angular2-tree-diagram inside node_modules.

**Comment by InnovationZone** [comment]
Even after having added the angular2-tree-diagram folder as an include in tsconfig.app.json to compile it.

`{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": [
      "xrm",
      "jquery",
      "jstree"
    ]
  },
  "files": [
    "../node_modules/angular2-tree-diagram/index.ts"
  ],
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
`


I'm getting an error saying: 

**ERROR in No NgModule metadata found for 'AppModule'**
